version: '2'
services:
  apache2:
    image: dr4g0nsr/apache2
    hostname: apache2
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/www/html:/var/www/html
      - ./apache2/config:/etc/apache2/sites-enabled
  php:
    image: dr4g0nsr/php55
    hostname: php
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/www/html:/var/www/html
      - ./php/config:/usr/local/etc
  mysql:
    image: dr4g0nsr/mysql57
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 34g345h34566j3567i3
      MYSQL_ROOT_HOST: localhost
      #MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: docker
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql_docker:/var/lib/mysql
      - ./mysql/config:/etc/mysql/mysql.conf.d
